---
Debian:
  repo:
    prerequisites:
      - apt-transport-https
      - ca-certificates
    config:
      # provided keyring file will be saved 'as is' in /etc/apt/keyrings/docker.asc
      # use this path for 'signed-by' value
      keyring: https://download.docker.com/linux/debian/gpg
      # sha256 hash for https://download.docker.com/linux/debian/gpg at 2025.04.10
      # if keyring_source_hash is not provided skip_verify: true will be used
      keyring_source_hash: sha256=1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570
      name: >
        deb [arch={{ grains.osarch }} signed-by=/etc/apt/keyrings/docker.asc]
        https://download.docker.com/linux/{{ grains.os|lower }} {{ grains.oscodename }} stable
      file: /etc/apt/sources.list.d/docker.list
      # apt-key is deprecated
      # key_url: https://download.docker.com/linux/{{ grains.os|lower }}/gpg
      refresh: true
  server:
    extra:
      pkgs:
        # python-docker package is mandatory, required for salt to communicate with docker daemon
        # but it have dependencies (python3-dockerpycreds -> golang-docker-credential-helpers)
        # which cause issues with 'docker login'
        # Since Salt 3006 onedir bundled pip will be used as main tool to install extra Python modules for Salt
        # for 'non onedir' Salt installations python3-docker is still required
        # - python3-docker
        - iptables
        - procps
        - pigz
        - xz-utils
        # install pass as a workaround for 'docker login' problem like:
        # Error saving credentials: error storing credentials - err: exit status 1, out:
        # `Cannot autolaunch D-Bus without X11 $DISPLAY`
        # yes there is about 10 packages will be installed as dependencies
        # but this is least intrusive solution
        # links to related bugs and discussions
        # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910822
        # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910823
        # https://stackoverflow.com/questions/51222996/docker-login-fails-on-a-server-with-no-x11-installed
        #
        # Upd 2025.04.30
        # It seems problem is fixed in recent versions of 'python-docker',
        # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910823#49
        # also since Salt 3006 pip 'docker' package is required, not system package.
        # Also with 'pass' package in Debian 12 125 extra packages will be installed.
        # Considering all the factors removing 'pass' from default packages list.
        #- pass
    pip:
      # system package with pip utility
      # since Salt 3006 onedir is a main installation variant for Salt and Salt onedir does have bundled pip
      # so additional package in not required in this case.
      package: ''
      # Salt onedir will use bundled pip and will install pip packages into Salt onedir venv, that's exactly what we need,
      # in this formula we only using pip to install extra Python modules (packages) solely for Salt itself
      # list of packages to install with pip
      pkgs:
        - docker

RedHat:
  repo:
    prerequisites: []
    config:
      name: docker-ce-stable
      humanname: Docker CE Stable - $basearch
      baseurl: https://download.docker.com/linux/{{ grains.os|lower }}/$releasever/$basearch/stable
      enabled: 1
      gpgcheck: 1
      gpgkey: https://download.docker.com/linux/{{ grains.os|lower }}/gpg
  server:
    extra:
      pkgs:
        # python-docker package is required for salt to communicate with docker daemon
        # but it's too old on CentOS, RedHat, pip package will be used
        - python3-dnf-plugin-versionlock # required for salt to hold a package version on RH derivatives
        - iptables
        - procps-ng
        - pigz
        - xz
    # install python pip packages sometimes it's required due lack
    # of fresh versions of software in system package repositories
    # i.e. python-docker package is not available or too old on CentOS, RedHat
    # https://github.com/saltstack/salt/issues/58920#issuecomment-726328964
    pip:
      # above statement is irrelevant since Salt 3006 onedir so by default no extra pip package required
      # package: python3-pip
      package: ''
      pkgs:
        - docker
