---
# os: Debian
Debian-12:
  server:
    tls:
      pkgs:
        - openssl

Debian-11:
  server:
    tls:
      pkgs:
        - openssl
        # not required when using Salt 3006 onedir and x509_v2 module
        # don't forget to enable x509_v2 in minion settings
        # - python3-m2crypto

Debian-10:
  server:
    tls:
      pkgs:
        - openssl
        # Preserving python3-m2crypto for systems on Debian 10 where most probably older version of Salt is used
        - python3-m2crypto
  repo:
    config:
      # Preserve legacy repo configuration for older systems
      keyring: ''
      keyring_source_hash: ''
      name: deb [arch=amd64] https://download.docker.com/linux/{{ grains.os|lower }} {{ grains.oscodename }} stable
      file: /etc/apt/sources.list.d/docker.list
      key_url: https://download.docker.com/linux/{{ grains.os|lower }}/gpg
      refresh: true

Debian-9:
  server:
    package:
      # Preserve package list without new docker plugins for Debian 9
      # new plugin packages is not available for Debian 9
      pkgs:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    tls:
      pkgs:
        - openssl
        - python-m2crypto
        # if you are using python 3
        # - python3-m2crypto
        # but it is not available in stretch or stretch-backports
  repo:
    config:
      # Preserve legacy repo configuration for older systems
      keyring: ''
      keyring_source_hash: ''
      name: deb [arch=amd64] https://download.docker.com/linux/{{ grains.os|lower }} {{ grains.oscodename }} stable
      file: /etc/apt/sources.list.d/docker.list
      key_url: https://download.docker.com/linux/{{ grains.os|lower }}/gpg
      refresh: true
  compose:
    # Try to install docker-compose v1 on Debian 9
    install: true
    shell_completion:
      bash:
        install: true

# os: CentOS
CentOS Linux-8:
  server:
    tls:
      pkgs:
        - openssl
        - python3-m2crypto

CentOS Linux-7:
  server:
    tls:
      pkgs:
        - openssl
        - python36-m2crypto
        # if you are using python 2
        # - m2crypto

# os: RedHat?
Red Hat Enterprise Linux Server-7: {}
