---
# os: Debian
Debian-10:
  server:
    tls:
      pkgs:
        - openssl
        - python3-m2crypto

Debian-9:
  server:
    tls:
      pkgs:
        - openssl
        - python-m2crypto
        # if you are using python 3
        # - python3-m2crypto
        # but it is not available in stretch or stretch-backports

# os: CentOS
CentOS Linux-8:
  server:
    tls:
      pkgs:
        - openssl
        - python3-m2crypto

CentOS Linux-7:
  server:
    tls:
      pkgs:
        - openssl
        - python36-m2crypto
        # if you are using python 2
        # - m2crypto

# os: RedHat?
Red Hat Enterprise Linux Server-7: {}
